### ISSUE TITLE
安卓7.0运行demo安装不了

### ISSUE THREAD

**Issue by weilixing00** [qiangxi/CheckUpdateLibrary#14]
一加3 android7.0 运行demo下载完后应用退出 但是没有安装界面

**Comment by qiangxi** [comment]
请问是最新版本的library吗?如果是的话,有没有按照readme的说明配置FileProvider?对于在7.0安装应用,library中已经做了适配了哦.

**Comment by weilixing00** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                       at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                       at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                       at com.qiangxi.checkupdatelibrary.utils.NotificationUtil.showDownloadSuccessNotification(NotificationUtil.java:44)
                                                       at com.qiangxi.checkupdatelibrary.service.DownloadService.downloadSuccess(DownloadService.java:50)
                                                       at com.qiangxi.checkupdatelibrary.service.BaseService$1.onDownloadSuccess(BaseService.java:58)
                                                       at com.qiangxi.checkupdatelibrary.http.HttpRequest$1.handleMessage(HttpRequest.java:81)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)

**Comment by weilixing00** [comment]
非强制更新报这个错，强制更新可以正常使用，目前还在排查

**Comment by weilixing00** [comment]
最新版的demo非强制更新7.0也崩，NotificationUtil中的 uri = FileProvider.getUriForFile(context, "com.qiangxi.checkupdatelibrary", file);  改成  uri = FileProvider.getUriForFile(context, "com.qiangxi.checkupdatelibrarydemo", file);  就正常，请修复

**Comment by mcxinyu** [comment]
对了，我怎么在 jcenter 中搜索不到呢？
![image](https://cloud.githubusercontent.com/assets/9566116/25832999/f2b66f24-34a0-11e7-900f-26455288f738.png)

**Comment by weilixing00** [comment]
NotificationUtil 这个类中 
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
           uri = FileProvider.getUriForFile(context, "com.qiangxi.checkupdatelibrary", file);
这样写 
ApplicationUtil这个类中
//当前设备系统版本在7.0以上
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            uri = FileProvider.getUriForFile(context, context.getPackageName(), file);
这样写   所以无论怎么设置 都是崩的
我吧项目clone下来  自己修改了下 好像好了
还有 最新的版本 compile 找不到 
其他地方做的还是不错的，继续加油！

**Comment by qiangxi** [comment]
@weilixing00 请问崩溃日志是什么?能发来看看嘛

**Comment by qiangxi** [comment]
@weilixing00 非强制更新方式下,7.0的崩溃问题已经修复了,请使用最新的1.1.2版本,通过context.getPackageName()这种方式我已经测试过了,没问题,如果你那里有什么问题,还请把具体的日志信息发上来look,look吧.
@mcxinyu 不管是jcenter还是Maven Central ，两者都是Maven仓库.
但两者之间没有多大关系,在jcenter上有的库可能 Maven Central 上没有，反之亦然。
我只把library上传到jcenter中,并没有同步到Maven Central中,
而从Android Studio中搜索默认是从Maven Central中搜索的,所以搜索不到.
