### ISSUE TITLE
情问为何我在弹出框的时候报错了

### ISSUE THREAD

**Issue by Rethen** [qiangxi/CheckUpdateLibrary#18]
Process: com.poseidon.pokers, PID: 24121
                                                                     android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class <unknown>
                                                                     Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class <unknown>
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                         at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                         at com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.onCreate(UpdateDialog.java:106)
                                                                         at android.app.Dialog.dispatchOnCreate(Dialog.java:395)
                                                                         at android.app.Dialog.show(Dialog.java:294)
                                                                         at com.szipcs.starpoker.ui.person.CurrentVersionActivity$1$1.run(CurrentVersionActivity.java:135)
                                                                         at android.app.Activity.runOnUiThread(Activity.java:5866)
                                                                         at com.szipcs.starpoker.ui.person.CurrentVersionActivity$1.onCheckUpdateSuccess(CurrentVersionActivity.java:123)
                                                                         at com.qiangxi.checkupdatelibrary.http.HttpRequest$1.handleMessage(HttpRequest.java:56)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                      Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f01005f a=-1}
                                                                         at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
                                                                         at android.view.View.<init>(View.java:4202)
                                                                         at android.widget.TextView.<init>(TextView.java:710)
                                                                         at android.widget.Button.<init>(Button.java:109)
                                                                         at android.widget.Button.<init>(Button.java:105)
                                                                         at android.widget.Button.<init>(Button.java:101)
                                                                         at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                         at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                         at com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.onCreate(UpdateDialog.java:106) 
                                                                         at android.app.Dialog.dispatchOnCreate(Dialog.java:395) 
                                                                         at android.app.Dialog.show(Dialog.java:294) 
                                                                         at com.szipcs.starpoker.ui.person.CurrentVersionActivity$1$1.run(CurrentVersionActivity.java:135) 
                                                                         at android.app.Activity.runOnUiThread(Activity.java:5866) 
                                                                         at com.szipcs.starpoker.ui.person.CurrentVersionActivity$1.onCheckUpdateSuccess(CurrentVersionActivity.java:123) 
                                                                         at com.qiangxi.checkupdatelibrary.http.HttpRequest$1.handleMessage(HttpRequest.java:56) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by qiangxi** [comment]
[看这个issue能解决你的问题吗](https://github.com/qiangxi/CheckUpdateLibrary/issues/9)
