### ISSUE TITLE
1.1.3@aar版本7.0系统强制更新异常

### ISSUE THREAD

**Issue by mavenjan** [qiangxi/CheckUpdateLibrary#19]
你好，有在用你写的checkupdatelibrary。更新过之后7.0强制更新报错 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.download()' on a null object reference
另，targetSdkVersion<23 的时候强制更新在弹出安装界面的时候报错
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

**Comment by qiangxi** [comment]
你好,我使用7.0版本的三星s7测试之后,未发现你说的崩溃情况哦.我测试了两种情况:app的targetSdkVersion=22和targetSdkVersion=25两种情况.

你可以结合readme再检查一下自己的代码,看看有没有readme说的你没有做到的,如果还是出现崩溃问题,还请把机型和版本号以及错误日志发上来看看

**Comment by mavenjan** [comment]
手动尴尬
我刚才用本地的library debug下，是我自己包名两次写的不一样，导致的错误，已修复。
但是下载最新的demo在华为mate9上运行，点强制更新，会崩溃抛出下面的异常。我用的2.3.2，gradle3.5在android studio 3.0上运行的
 FATAL EXCEPTION: main
                                                                                    Process: com.qiangxi.checkupdatelibrarydemo, PID: 22941
                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.qiangxi.checkupdatelibrarydemo/com.qiangxi.checkupdatelibrarydemo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.download()' on a null object reference
                                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
                                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
                                                                                        at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.download()' on a null object reference
                                                                                        at com.qiangxi.checkupdatelibrarydemo.MainActivity.onRequestPermissionsResult(MainActivity.java:166)
                                                                                        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7340)
                                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:7192)
                                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)
                                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327) 
                                                                                        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                        at android.os.Looper.loop(Looper.java:156) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6531) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by qiangxi** [comment]
从崩溃日志上看,dialog为null,调用download方法必然空指针.但是讲道理的话,在调用download的方法的时候,dialog必不可能是null的,不过为了保险起见,我已经修改demo,对null进行的检查.我有机会会用华为mate9测试的.

**Comment by mavenjan** [comment]
好的，谢谢分享哈。学习了
