### ISSUE TITLE
Binary XML file line #84: Error inflating class

### ISSUE THREAD

**Issue by zghkevin** [qiangxi/CheckUpdateLibrary#9]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.highjy.gaoqi, PID: 4852
                  android.view.InflateException: Binary XML file line #84: Error inflating class <unknown>
                      at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                      at com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.onCreate(UpdateDialog.java:82)
                      at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
                      at android.app.Dialog.show(Dialog.java:274)
                      at com.highjy.gaoqi.MainActivity.showUpdateDialog(MainActivity.java:291)
                      at com.highjy.gaoqi.MainActivity$7$1.run(MainActivity.java:259)
                      at android.app.Activity.runOnUiThread(Activity.java:5293)
                      at com.highjy.gaoqi.MainActivity$7.onCheckUpdateSuccess(MainActivity.java:256)
                      at com.qiangxi.checkupdatelibrary.http.HttpRequest$1.handleMessage(HttpRequest.java:56)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.onCreate(UpdateDialog.java:82) 
                      at android.app.Dialog.dispatchOnCreate(Dialog.java:373) 
                      at android.app.Dialog.show(Dialog.java:274) 
                      at com.highjy.gaoqi.MainActivity.showUpdateDialog(MainActivity.java:291) 
                      at com.highjy.gaoqi.MainActivity$7$1.run(MainActivity.java:259) 
                      at android.app.Activity.runOnUiThread(Activity.java:5293) 
                      at com.highjy.gaoqi.MainActivity$7.onCheckUpdateSuccess(MainActivity.java:256) 
                      at com.qiangxi.checkupdatelibrary.http.HttpRequest$1.handleMessage(HttpRequest.java:56) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                   Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 13
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:747)
                      at android.view.View.<init>(View.java:3737)
                      at android.widget.TextView.<init>(TextView.java:637)
                      at android.widget.Button.<init>(Button.java:111)
                      at android.widget.Button.<init>(Button.java:107)
                      at android.widget.Button.<init>(Button.java:103)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at com.qiangxi.checkupdatelibrary.dialog.UpdateDialog.onCreate(UpdateDialog.java:82) 
                      at android.app.Dialog.dispatchOnCreate(Dialog.java:373) 
                      at android.app.Dialog.show(Dialog.java:274) 

以下是调用代码
          mUpdateDialog = new UpdateDialog(MainActivity.this);
            mUpdateDialog.setAppSize(mCheckUpdateInfo.getNewAppSize())
                    .setDownloadUrl(mCheckUpdateInfo.getNewAppUrl())
                    .setTitle(mCheckUpdateInfo.getAppName() + "有更新啦")
                    .setReleaseTime(mCheckUpdateInfo.getNewAppReleaseTime())
                    .setVersionName(mCheckUpdateInfo.getNewAppVersionName())
                    .setUpdateDesc(mCheckUpdateInfo.getNewAppUpdateDesc())
                    .setFileName("gaoqi.apk")
                    .setFilePath(Environment.getExternalStorageDirectory().getPath() + "/checkupdatelib")
                    //该方法需设为true,才会在通知栏显示下载进度,默认为false,即不显示
                    //该方法只会控制下载进度的展示,当下载完成或下载失败时展示的通知不受该方法影响
                    //即不管该方法是置为false还是true,当下载完成或下载失败时都会在通知栏展示一个通知
                    .setShowProgress(true)
                    .setIconResId(R.mipmap.ic_launcher)
                    .setAppName(mCheckUpdateInfo.getAppName()).show();

调用show的时候就报错了。怎么弄。。

**Comment by mcxinyu** [comment]
我也出现了类似的错误，
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.about.zhiye, PID: 11035
                                                                 android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class android.widget.Button
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                     at com.qiangxi.checkupdatelibrary.dialog.ForceUpdateDialog.onCreate(ForceUpdateDialog.java:83)
                                                                     at android.app.Dialog.dispatchOnCreate(Dialog.java:404)
                                                                     at android.app.Dialog.show(Dialog.java:301)
                                                                     at com.about.zhiye.fragment.PreferencesFragment.forceUpdateDialogClick(PreferencesFragment.java:138)
                                                                     at com.about.zhiye.fragment.PreferencesFragment$1.onSuccess(PreferencesFragment.java:97)
                                                                     at im.fir.sdk.j.run(Client.java:370)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5963)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
                                                                  Caused by: android.view.InflateException: Binary XML file line #94: Error inflating class android.widget.Button
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                     at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                     at com.qiangxi.checkupdatelibrary.dialog.ForceUpdateDialog.onCreate(ForceUpdateDialog.java:83) 
                                                                     at android.app.Dialog.dispatchOnCreate(Dialog.java:404) 
                                                                     at android.app.Dialog.show(Dialog.java:301) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment.forceUpdateDialogClick(PreferencesFragment.java:138) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment$1.onSuccess(PreferencesFragment.java:97) 
                                                                     at im.fir.sdk.j.run(Client.java:370) 
                                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5963) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                     at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                     at com.qiangxi.checkupdatelibrary.dialog.ForceUpdateDialog.onCreate(ForceUpdateDialog.java:83) 
                                                                     at android.app.Dialog.dispatchOnCreate(Dialog.java:404) 
                                                                     at android.app.Dialog.show(Dialog.java:301) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment.forceUpdateDialogClick(PreferencesFragment.java:138) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment$1.onSuccess(PreferencesFragment.java:97) 
                                                                     at im.fir.sdk.j.run(Client.java:370) 
                                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5963) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
                                                                  Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f01009d a=-1}
                                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
                                                                     at android.view.View.<init>(View.java:4039)
                                                                     at android.widget.TextView.<init>(TextView.java:725)
                                                                     at android.widget.Button.<init>(Button.java:109)
                                                                     at android.widget.Button.<init>(Button.java:105)
                                                                     at android.widget.Button.<init>(Button.java:101)
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                     at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                     at com.qiangxi.checkupdatelibrary.dialog.ForceUpdateDialog.onCreate(ForceUpdateDialog.java:83) 
                                                                     at android.app.Dialog.dispatchOnCreate(Dialog.java:404) 
                                                                     at android.app.Dialog.show(Dialog.java:301) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment.forceUpdateDialogClick(PreferencesFragment.java:138) 
                                                                     at com.about.zhiye.fragment.PreferencesFragment$1.onSuccess(PreferencesFragment.java:97) 
                                                                     at im.fir.sdk.j.run(Client.java:370) 
                                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5963) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) `

**Comment by mcxinyu** [comment]
ForceUpdateDialog 的构造函数如果传入的是 Application 的 content 会导致 android.view.LayoutInflater.inflate 失败。传入 Activity 才可以。

**Comment by qiangxi** [comment]
@mcxinyu 
1. Dialog的展示需要传入Activity的上下文哦,传入Application 的上下文肯定是不行的.因为Dialog需要依附于Activity展示.
2. 如果可以的话.上面的异常能详细说说是怎么产生的吗?可以从以下几方面说说:
(1).在Activity中或在Fragment中调用的?
(2). 调用的时候所在线程是主线程吗?
(3). App的minVersion和targetVersion各是多少?
(4),测试的机型是什么品牌,什么版本?
(5),具体是什么情况下崩溃的?

**Comment by mcxinyu** [comment]
其实构造函数中你可以把参数改为 Activity 做 context，而且你下面的exitButton也不用转型了。

魅族pro6、android6.0；在fragment中调用、主线程；minSdkVersion 19、targetSdkVersion 25；

其实就是传入Application 做上下文导致出错。

**Comment by qiangxi** [comment]
恩,问题解决了就好.
对于exitButton,虽然它只有添加点击事件这一个作用,但是个人认为还是要完整的写出来,首先代码看起来相对有条理,其次如果以后加入新功能可以直接用了.看个人的编码习惯吧
